name: Build Docker image & Publish to ECR
on:
  workflow_dispatch:

env:
  AWS_ECR_REGION: ${{ vars.AWS_ECR_REGION }}

jobs:
  ECR_Airflow_Deployment:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-aws#adding-permissions-settings
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      # - name: Debug OIDC token claims
      #   run: |
      #     IDTOKEN=$(curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
      #       "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
      #     echo "$IDTOKEN" | cut -d '.' -f2 | base64 -d 2>/dev/null | jq .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.1
        env:
          AWS_IAM_ROLE_ARN: ${{ vars.AWS_IAM_ROLE_ARN }}
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}
          role-session-name: Github-Actions-Session
          aws-region: ${{ env.AWS_ECR_REGION }}
          output-credentials: true

      - name: Get Caller Identity
        run: |
          aws sts get-caller-identity
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.AWS_ECR_REPOSITORY }}
          ECR_IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_TAG
